# PocketBase docker-compose for local-first Kilo Code cloud
# Usage: docker compose -f packages/cloud/docker/docker-compose.pocketbase.yml --profile cloud up -d
# Notes:
# - PocketBase persists data to ./pb_data (relative to this docker-compose file)
# - Admin user creation can be done via the PocketBase admin UI after first start or via the CLI
# - Exposes 8090 on the host for the extension/local dev server to talk to
version: "3.8"

services:
  pocketbase:
    image: ghcr.io/pocketbase/pocketbase:0.13.1
    container_name: kilocode-pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
    command: ["serve", "--http=0.0.0.0:8090", "--dir", "/pb_data"]
    environment:
      - POCKETBASE_ENV=dev
    networks:
      - kilocode-network
    profiles:
      - cloud

volumes:
  pb_data:

networks:
  kilocode-network:
    driver: bridge